Citizen.CreateThread(function()
    --AddTextEntry('spawncode', 'LABEL')
    AddTextEntry ('offlrds1000',      'Ninja Kawasaki'             )
    AddTextEntry ('gs310',            'G310 BMW'                   )
    --- COMPACTOS
    AddTextEntry ('aventador',        'Aventador Lamborghini'      )
    --- COUPES 
    AddTextEntry ('cyrus',            'DBS Aston Martin'           )
    AddTextEntry ('rs6+',             'RS6+ Audi'                  )
    --- OFF-ROAD 
    AddTextEntry ('DragNova',         'SS Chevy'                   )
    AddTextEntry ('iak_wheelchair',   'Xavier AACD'                )
    --- SUPER 
    AddTextEntry ('rx7v',             'RX7 97 Mazda'               )
    AddTextEntry ('mclaren765',       '765LT McLaren'              )
    AddTextEntry ('ocnlamtmc',        'Terzo Millenio Lamborghini' )
    AddTextEntry ('TecnidaTDB',       'Huracan Lamborghini'        )
    AddTextEntry ('lamrevuelto',      'Revuelto Lamborghini'       )
    AddTextEntry ('Revuelto',         'Revuelto S Lamborghini'     )
    AddTextEntry ('gtr',              'Skyline GTR35 Nissan'       )
    AddTextEntry ('bmgolfr',          'Golf 2025 Volkswagen'       )
    AddTextEntry ('fsf90xx',          'SF90XX Ferrari'             )
    AddTextEntry ('essenzascv12',     'Centenario Lamborghini'     )
    AddTextEntry ('chiron',           'Chiron Bugatti'             )
    AddTextEntry ('bolide',           'Bolide Bugatti'             )
    AddTextEntry ('aimgainnsx',       'NSX Acura'                  )
    AddTextEntry ('r8v10abt',         'R8 Audi'                    )
    AddTextEntry ('r820',             'R820 Audi'                  )
    --- ESPORTIVOS
    AddTextEntry ('wrx19',            'WRX 19 Subaru'              )
    AddTextEntry ('variszupra',       'Supra A80 Toyota'           )
    AddTextEntry ('ss16',             'Camaro SS16 Chevrolet'      )
    AddTextEntry ('nissanr33tbk',     'Skyline GTR33 Nissan'       )
    AddTextEntry ('m3gtr',            'M3 GTR BMW'                 )
    AddTextEntry ('huayrar',          'Huayra R Pagani'            )
    AddTextEntry ('skyline',          'Skyline GTR34 Nissan'       )
    AddTextEntry ('f488pista',        '488 Ferrari'                )
    AddTextEntry ('casup',            'Supra Drift Toyota'         )
    AddTextEntry ('12charger',        'Super Charger Dodge'        )
    --- POTENTES 
    AddTextEntry ('69charger',        '69 Charger Dodge'           )
    AddTextEntry ('redeye',           'SRT Charger Dodge'          )
    --- SEDANS 
    AddTextEntry ('nisa31',           'Cefiro A31'                 )               
end)